name: Check SwissPedose Release

on:
  schedule:
    - cron: "0 9 * * *"  # Runs every day at 9 AM UTC
  workflow_dispatch:  # Allow manual runs

jobs:
  check_release:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the repository
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      
      # Step 2: Set up Git credentials (for committing updates)
      - name: Set up Git credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      
      # Step 3: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 4: Install Python dependencies
      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml

      # Step 5: Run the script
      - name: Run script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python check_release.py
      
      # Step 6: Check for file changes
      - name: Check if file changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add last_release_date.txt
            git commit -m "Update last release date [skip ci]"
          else
            echo "No changes to commit."
          fi

      # Step 7: Push changes if any
      - name: Push changes
        if: always()
        run: git push
        env:
          # Use GitHub token from the default secret, which has write permissions if workflow permissions are properly set
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}