name: Check SwissPedose Release
on:
  schedule:
    - cron: "0 9 * * *"  # Runs every day at 9 AM UTC
  workflow_dispatch:  # Allow manual runs

jobs:
  check_release:
    runs-on: ubuntu-latest

    steps:

      - name: Check Telegram env vars
        run: |
          if [ -z "${{ secrets.TELEGRAM_BOT_TOKEN }}" ]; then echo "TELEGRAM_BOT_TOKEN not set"; else echo "TELEGRAM_BOT_TOKEN is set"; fi
          if [ -z "${{ secrets.TELEGRAM_CHAT_ID }}" ]; then echo "TELEGRAM_CHAT_ID not set"; else echo "TELEGRAM_CHAT_ID is set"; fi

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4 lxml

      - name: Run script
        env:
          # Telegram credentials
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          # SMTP credentials for Gmail
          EMAIL_FROM: ${{ secrets.EMAIL_FROM }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_TO: ${{ secrets.EMAIL_TO }}    # recipient address (pipeline secret)
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }} # app password for Gmail SMTP
        run: python check_release.py

      - name: Set up GitHub authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}

      - name: Configure Git author
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Check if file changed
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git add last_release_date.txt
            git commit -m "Update last release date [skip ci]"
          else
            echo "No changes to commit."
          fi

      - name: Push changes
        if: always()
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
